[package]
name = "axprocess"
version = "0.1.0"
edition = "2024"
authors = ["Asakura Mizu <asakuramizu111@gmail.com>"]
description = "Process management for ArceOS"

[dependencies]
kspin = "0.1"

[dev-dependencies]
kspin = { version = "0.1", features = ["smp"] }
