[package]
name = "axprocess"
version = "0.1.0"
edition = "2024"
authors = ["Asakura Mizu <asakuramizu111@gmail.com>"]
description = "Process management for ArceOS"

[dependencies]
kspin = "0.1"
lazyinit = "0.2.1"
weak-map = { git = "https://github.com/Starry-OS/weak-map" }

[dev-dependencies]
ctor = "0.4.1"
kspin = { version = "0.1", features = ["smp"] }
